name: Auto-Create Issue If DB Column Changed

on:
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          `cat <<EOS > title
          $(date +'%Y.%m.%d') test
          EOS`

          `cat <<EOS > body
          ## test
          - [ ] test 1
          - [ ] test 2
            - test 2-1
            - test 2-2
            - test 2-3

          ＜testing＞
          EOS`

          gh issue create --repo $GITHUB_REPOSITORY \
                          --title "$(cat title)" \
                          --body "$(cat body)" \
                          --label "test,test2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
